language: node_js
node_js:
- '7.6'
deploy:
  provider: npm
  email: 86287344@qq.com
  skip_cleanup: true
  api_key:
    secure: gYlrZq6AvtAKxHPOZk/R/f9s9O9QJSz0xlH/C6IKugGtlqBhXxIJkjJmW59GpN5eJu6Z1tDypxUCjPvJRXDhleKvz+QZ/CRfsCeYxpRcH3nCoWTc28tnJbTccwtypd9ioirL2qch7t7m5EQ1nHuL4X/hEoeztCqu+wu4e0kbKDO2mlUhfozRhE47/5SOq4GcshWbwfvSCdW/3oe43i7NJAnz2B4SZH7PR2MqRWkmciBmkEsEYPrtcBLMcUs4EwFwROtU8ww74gfMg1LOsZD0idTLvwcx/jfkgMkEKtaM6cXjZbW0c13oG3DxBFexpAMZLywA0bOIwI5GPEDDXTTEHtx5th2c/D97C17QxRm3osI6anuPcJJzkoqmOUhKA0OFUFb5AjnKYIV9opL4GcEQ3weAVe5zXQnUrJdCoaV56cUj7M8gH2dCRHJZ4zc949KW8rN1XJBVUSdc+Op/qcu7h8aGIlSLAIT0ikxS342G3InenzsmNoPJmMT7rKi4xjX3+c4adsRECK+EcehfpinfXGg4AH6XH3lj2LMEoIdACtHnhQKyFS7BpbzM9mAmGOPFTUSSS1Kuj59Of8nDDka2Qj4S8nSBIr/48O77Fp2UCUKvCPw6AQDZl4mgGhXLtvK0BtW6bMJpFRzn+3NVgres9N1WK2vHC2j0dCZkbf/EIXw=
